import{createServer}from'node:http';import{DatabaseSync}from'node:sqlite';import{readFileSync,writeFileSync,existsSync,mkdirSync,readdirSync}from'node:fs';import{resolve,extname}from'node:path';import{randomBytes,createHmac,timingSafeEqual}from'node:crypto';
import worker from '../dist/server/local.js';
import{setLocalEnv}from'../dist/server/local.js';
const dataDir=process.env.DATA_DIR||'.local';mkdirSync(dataDir,{recursive:true});
if(!existsSync(resolve(dataDir,'admin-key')))writeFileSync(resolve(dataDir,'admin-key'),randomBytes(18).toString('base64url'));
const password=process.env.ADMIN_PASSWORD||readFileSync(resolve(dataDir,'admin-key'),'utf8').trim();
const secret=readFileSync(resolve(dataDir,'admin-key'),'utf8');
const sqlite=new DatabaseSync(resolve(dataDir,'votes.sqlite'));sqlite.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;');
sqlite.exec('CREATE TABLE IF NOT EXISTS local_migrations (name TEXT PRIMARY KEY)');
for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort()){if(!sqlite.prepare('SELECT name FROM local_migrations WHERE name=?').get(file)){sqlite.exec('BEGIN');try{sqlite.exec(readFileSync('drizzle/'+file,'utf8'));sqlite.prepare('INSERT INTO local_migrations VALUES (?)').run(file);sqlite.exec('COMMIT')}catch(e){sqlite.exec('ROLLBACK');throw e}}}
function prepared(sql,values=[]){return{bind(...v){return prepared(sql,v)},async first(){return sqlite.prepare(sql).get(...values)||null},async all(){return{results:sqlite.prepare(sql).all(...values)}},async run(){const r=sqlite.prepare(sql).run(...values);return{meta:{changes:Number(r.changes)}}}}}
const DB={prepare:prepared,async batch(items){sqlite.exec('BEGIN IMMEDIATE');try{const result=[];for(const item of items)result.push(await item.run());sqlite.exec('COMMIT');return result}catch(e){sqlite.exec('ROLLBACK');throw e}}};
function signature(v){return createHmac('sha256',secret).update(v).digest('base64url')}
function authorized(cookie){const token=/(?:^|; )pv_admin=([^;]+)/.exec(cookie||'')?.[1];if(!token)return false;const [expires,sig]=token.split('.');return Number(expires)>Date.now()&&sig===signature(expires)}
setLocalEnv({DB,ASSETS:{async fetch(request){let path=new URL(request.url).pathname;if(path==='/'||/^\/v\/[^/]+$/.test(path))path='/index.html';const file=resolve('dist/client','.'+decodeURIComponent(path));if(!file.startsWith(resolve('dist/client')+'/')&&!file.startsWith(resolve('dist/client')+'\\'))return new Response('No disponible',{status:404});try{return new Response(readFileSync(file),{headers:{'Content-Type':({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml'})[extname(file)]||'application/octet-stream'}})}catch{return new Response('No encontrado',{status:404})}}}});
const host=process.env.HOST||'127.0.0.1',port=Number(process.env.PORT||4173);
const server=createServer(async(req,res)=>{try{const origin=process.env.PUBLIC_URL||'http://'+req.headers.host;const url=new URL(req.url,origin);let content=Buffer.alloc(0);for await(const part of req){content=Buffer.concat([content,part]);if(content.length>10000){res.writeHead(413);res.end();return}}
if(url.pathname==='/signin-with-chatgpt'){
if(req.method==='POST'){if(req.headers.origin&&req.headers.origin!==origin){res.writeHead(403);res.end();return}const supplied=new URLSearchParams(content.toString()).get('password')||'';const a=Buffer.from(supplied),b=Buffer.from(password);if(a.length===b.length&&timingSafeEqual(a,b)){const expiry=String(Date.now()+12*60*60*1000);res.writeHead(303,{'Location':'/','Set-Cookie':'pv_admin='+expiry+'.'+signature(expiry)+'; HttpOnly; SameSite=Lax; Path=/; Max-Age=43200'+(origin.startsWith('https:')?'; Secure':'')});res.end();return}}
res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end('<!doctype html><html lang="es"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/app.css"><title>Entrar · Palabra Viva</title><main class="votecontainer"><p class="eyebrow">PALABRA VIVA · ORGANIZADOR</p><h1>Entra en tu espacio</h1><p>Usa la contraseña que aparece al iniciar la aplicación en tu ordenador.</p>'+(req.method==='POST'?'<p class="notice">Contraseña incorrecta.</p>':'')+'<form method="post"><label>Contraseña<input name="password" type="password" required autocomplete="current-password"></label><button class="primary">Entrar</button></form></main></html>');return}
if(url.pathname==='/signout-with-chatgpt'){res.writeHead(303,{'Location':'/','Set-Cookie':'pv_admin=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0'});res.end();return}
const headers=new Headers();for(const[k,v]of Object.entries(req.headers)){if(v&&!k.startsWith('oai-'))headers.set(k,Array.isArray(v)?v.join(','):v)}if(authorized(req.headers.cookie)){headers.set('oai-authenticated-user-id','local-owner');headers.set('oai-authenticated-user-email','organizador@local.invalid')}
const request=new Request(url,{method:req.method,headers,...(!['GET','HEAD'].includes(req.method)?{body:content}: {})});const response=await worker.fetch(request);res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));
}catch(e){console.error(e);res.writeHead(500);res.end('No se ha podido completar la solicitud.')}});
server.listen(port,host,()=>console.log('Palabra Viva: '+(process.env.PUBLIC_URL||'http://'+host+':'+port)+'\n'+(process.env.ADMIN_PASSWORD?'Contraseña configurada en ADMIN_PASSWORD.':'Contraseña del organizador: '+password)+'\nDatos: '+dataDir+'\nMantén esta ventana abierta.'));


